### PR TITLE
Fix filter by content by link reference's id

### LINKED ISSUE #284: Unable to filter by link reference ID
- contentful.swift version number: 5.0.5
- Xcode version number: 10.3
- Target operating system(s) and version number(s)
  - [x] iOS: 
  - [ ] tvOS: 
  - [ ] watchOS:
  - [ ] macOS:
- Package manager:
  - [ ] Carthage
  - [x] Cocoapods

It looks like the SDK is unable to filter content by its link reference's ID. 

Suppose I have two content models, `Product` and `Category`. A product has a field `category` which is of type `Category`. In the app, I stored some category IDs, and I want to get products under these categories.

Here's the code I tried:

```swift
let categoryIds = [...]
let categoryConstraints = LinkQuery<Category>.where(sys: Sys.CodingKeys.id, .includes(categoryIds))

var query = QueryOn<Product>
                .include(1)
                .where(linkAtField: .category, matches: categoryConstraints)
```

However, the query simply drops the ID constraint when generating the URL.

By looking into the code, I found `.where(sys: _ operation:)` exists in the AbstractQuery.

```swift
static func `where`(sys key: Sys.CodingKeys, _ operation: Query.Operation) -> Self {
    return Self.where(valueAtKeyPath: "sys.\(key.stringValue)", operation)
}

static func `where`(valueAtKeyPath keyPath: String, _ operation: Query.Operation) -> Self {
    let parameter = keyPath + operation.string

    let query = Self()
    query.parameters[parameter] = operation.values

    return query
}
```

The code above doesn't set LinkQuery's `propertyName` which is required by `QueryOn`'s `where(linkAtField:matches:)`:

```swift
public func `where`<LinkType>(linkAtField fieldsKey: EntryType.FieldKeys,
                                                    matches linkQuery: LinkQuery<LinkType>) -> QueryOn<EntryType> {

    parameters["fields.\(fieldsKey.stringValue).sys.contentType.sys.id"] = LinkType.contentTypeId

    // If propertyName isn't unrwrapped, the string isn't constructed correctly for some reason.
    if let propertyName = linkQuery.propertyName {
        let filterParameterName = "fields.\(fieldsKey.stringValue).\(propertyName)\(linkQuery.operation.string)"
        parameters[filterParameterName] = linkQuery.operation.values
    }
    return self
}
``` 

You can see here, the `propertyName` will be nil and the ID constraints will be dropped.

### PR DESCRIPTION
**Pull request by tomkowz**
- Exposed method that allows filtering content by link reference's id.
- Added test

Resolves #284

### CODE REVIEW

File: Sources/Contentful/TypedQuery.swift [hunk 1]
```diff
@@ -63,6 +63,35 @@ public final class LinkQuery<EntryType>: AbstractQuery where EntryType: EntryDec
         return LinkQuery<EntryType>.with(valueAtKeyPath: "fields.\(field.stringValue)", operation)
     }
 
+    /// Static method for creating a new LinkQuery with an operation. This variation for initializing guarantees
```
Comment (makinwab) [inline Sources/Contentful/TypedQuery.swift:66]: Nitpick - better to use the multi-line comment style` /** ... */`

Comment (tomkowz) [reply Sources/Contentful/TypedQuery.swift:66]: Sure, will do. I just wanted to stick to what we have in the codebase right now. But you're right.
